__title__ = 'MindsDB Predict handler'
__package_name__ = 'mindsdb_Predict_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for PredictHQ"
__author__ = 'MindsDB Inc'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'GPL-3.0'
__copyright__ = 'Copyright 2023- mindsdb'
